version: "3.2"
services:

 redis:
    image: "redis:alpine"

    command: redis-server
    container_name: rappi-redis
    ports:
     - "6380:6379"

    environment:
     - REDIS_REPLICATION_MODE=master